# Generated by Django 3.2.5 on 2021-07-16 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='edit_by',
            new_name='name',
        ),
    ]
