# Generated by Django 3.2.5 on 2021-07-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0003_auto_20210716_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
