# Generated by Django 3.2.5 on 2021-07-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0004_alter_note_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64)),
                ('year', models.IntegerField()),
                ('category', models.CharField(choices=[('Semester', 'Semester'), ('Sessional-I', 'Sessional-I'), ('Sessional-II', 'Sessional-Ii')], max_length=12)),
            ],
        ),
    ]
