# Generated by Django 3.2.5 on 2021-07-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0005_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.IntegerField(default=2021),
        ),
    ]
