# Generated by Django 3.2.5 on 2021-07-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0007_alter_paper_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='category',
            field=models.CharField(choices=[('Semester', 'Semester'), ('Sessional-I', 'Sessional-I'), ('Sessional-II', 'Sessional-Ii')], max_length=12),
        ),
        migrations.AlterField(
            model_name='paper',
            name='subject',
            field=models.CharField(choices=[('AD-1', 'Ad-1'), ('PD-I', 'Pd-I'), ('AD-II', 'Ad-Ii'), ('PD-II', 'Pd-Ii'), ('Biotech', 'Biotech')], max_length=32),
        ),
    ]
