# Generated by Django 3.2.5 on 2021-07-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0008_auto_20210716_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='paper_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
