# Generated by Django 3.2.5 on 2021-07-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0009_paper_paper_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
    ]
