# Generated by Django 3.2.5 on 2021-07-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0011_alter_paper_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='paper',
            name='moon',
            field=models.CharField(choices=[('Apollo 11 (Eagle)', 'Apollo 11'), ('Apollo 12 (Intrepid)', 'Apollo 12')], default='', max_length=32),
        ),
    ]
