# Generated by Django 3.2.5 on 2021-07-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0015_auto_20210716_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
