# Generated by Django 3.2.5 on 2021-08-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0016_alter_paper_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='image',
        ),
        migrations.AddField(
            model_name='paper',
            name='file_url',
            field=models.URLField(default=''),
        ),
    ]
