# Generated by Django 3.2.5 on 2021-08-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0017_auto_20210826_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='title',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='paper',
            name='uploader',
            field=models.CharField(default='', max_length=64),
        ),
    ]
