# Generated by Django 3.2.5 on 2021-08-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0019_auto_20210829_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='source',
            field=models.CharField(default='', max_length=164),
        ),
    ]
