# Generated by Django 3.2.5 on 2021-08-30 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0021_note_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date',
        ),
    ]
